apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component}}-service
spec:
  selector:
    component: {{ .Values.component}}-deployment
  ports:
    - protocol: TCP
      port: {{ .Values.port}}
      targetPort: {{ .Values.port}}